"""Functions for executing queries and mutations using Rekuest Next and Rath.

This function hook into the api funciton that are autogenerated by turms and
allow you to execute queries and mutations using thre rekuest-rath client.

Middleware Support:
    The execute/subscribe functions support a middleware chain that
    processes serialized variables before they reach the rath link chain.
    Middleware is configured on the MikroNextRath instance via its
    `middlewares` field.

    Two distinct paths are provided:
        - Sync (execute/subscribe): Calls middleware.process_variables()
          which uses sync I/O (e.g., obstore for S3 uploads).
        - Async (aexecute/asubscribe): Calls middleware.aprocess_variables()
                    which uses async I/O (e.g., obstore for S3 uploads).

"""

from collections.abc import AsyncGenerator, Generator
from typing import Any

from koil import unkoil_gen
from rath.turms.funcs import TOperation

from mikro_next.rath import MikroNextRath, current_mikro_next_rath

from .errors import NoMikroFound
from .middleware.base import FuncsMiddleware


def _apply_middlewares_sync(
    variables: dict[str, Any],
    operation: type[TOperation],
    rath: MikroNextRath,
    middlewares: list[FuncsMiddleware],
) -> dict[str, Any]:
    """Apply the middleware chain to the serialized variables (sync path).

    Each middleware processes the variables in order using its sync
    ``process_variables`` method. This happens *after* pydantic
    serialization (model_dump) but *before* the operation is sent to rath.

    Args:
        variables: The serialized variables dict.
        operation: The operation type being executed.
        rath: The rath client instance.
        middlewares: The list of middleware to apply.

    Returns:
        The fully processed variables dict.
    """
    for middleware in middlewares:
        variables = middleware.process_variables(variables, operation, rath)
    return variables


async def _apply_middlewares_async(
    variables: dict[str, Any],
    operation: type[TOperation],
    rath: MikroNextRath,
    middlewares: list[FuncsMiddleware],
) -> dict[str, Any]:
    """Apply the middleware chain to the serialized variables (async path).

    Each middleware processes the variables in order using its async
    ``aprocess_variables`` method.

    Args:
        variables: The serialized variables dict.
        operation: The operation type being executed.
        rath: The rath client instance.
        middlewares: The list of middleware to apply.

    Returns:
        The fully processed variables dict.
    """
    for middleware in middlewares:
        variables = await middleware.aprocess_variables(variables, operation, rath)
    return variables


def execute(
    operation: type[TOperation],
    variables: dict[str, Any],
    rath: MikroNextRath | None = None,
) -> TOperation:
    """Executes a query or mutation using rath in a blocking way.

    Uses the sync middleware path (process_variables) which runs
    uploads via obstore in the calling thread.
    """
    rath = rath or current_mikro_next_rath.get()
    if not rath:
        raise NoMikroFound("No rath client found in context. Please provide a rath client.")

    # First serialize through operation.Arguments (pydantic validation + alias resolution)
    serialized = operation.Arguments(**variables).model_dump(by_alias=True, exclude_unset=True)

    # Apply sync middleware chain (e.g., upload arrays via obstore)
    serialized = _apply_middlewares_sync(serialized, operation, rath, rath.middlewares)

    x = rath.query(
        operation.Meta.document,
        serialized,
    )
    return operation(**x.data)


async def aexecute(
    operation: type[TOperation],
    variables: dict[str, Any],
    rath: MikroNextRath | None = None,
) -> TOperation:
    """Executes a query or mutation using rath in a non-blocking way.

    Uses the async middleware path (aprocess_variables) which runs
    uploads via obstore.
    """
    rath = rath or current_mikro_next_rath.get()
    if not rath:
        raise NoMikroFound("No rath client found in context. Please provide a rath client.")

    # First serialize through operation.Arguments (pydantic validation + alias resolution)
    serialized = operation.Arguments(**variables).model_dump(by_alias=True, exclude_unset=True)

    # Apply async middleware chain (e.g., upload arrays via obstore)
    serialized = await _apply_middlewares_async(serialized, operation, rath, rath.middlewares)

    x = await rath.aquery(
        operation.Meta.document,
        serialized,
    )
    return operation(**x.data)


def subscribe(
    operation: type[TOperation],
    variables: dict[str, Any],
    rath: MikroNextRath | None = None,
) -> Generator[TOperation, None, None]:
    """Subscribes to a query or mutation using rath in a blocking way."""
    return unkoil_gen(asubscribe, operation, variables, rath)


async def asubscribe(
    operation: type[TOperation],
    variables: dict[str, Any],
    rath: MikroNextRath | None = None,
) -> AsyncGenerator[TOperation, None]:
    """Subscribes to a query or mutation using rath in a non-blocking way.

    Uses the async middleware path (aprocess_variables).
    """
    rath = rath or current_mikro_next_rath.get()
    if not rath:
        raise NoMikroFound("No rath client found in context. Please provide a rath client.")

    # First serialize through operation.Arguments (pydantic validation + alias resolution)
    serialized = operation.Arguments(**variables).model_dump(by_alias=True, exclude_unset=True)

    # Apply async middleware chain
    serialized = await _apply_middlewares_async(serialized, operation, rath, rath.middlewares)

    async for event in rath.asubscribe(
        operation.Meta.document,
        serialized,
    ):
        yield operation(**event.data)
