projects:
  mikro:
    schema: http://localhost:8080/graphql
    documents: graphql/*/**.graphql
    extensions:
      turms:
        out_dir: mikro/api
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operation.OperationsPlugin
            query_bases:
              - mikro.operation.GraphQLQuery
            mutation_bases:
              - mikro.operation.GraphQLMutation
            subscription_bases:
              - mikro.operation.GraphQLSubscription
          - type: turms.plugins.funcs.OperationsFuncPlugin
        processors:
          - type: turms.processor.black.BlackProcessor
        scalar_definitions:
          XArray: mikro.scalars.XArray
          File: mikro.scalars.File
          ImageFile: mikro.scalars.File
          Upload: mikro.scalars.Upload
          DataFrame: mikro.scalars.DataFrame
          Store: mikro.scalars.Store
        additional_bases:
          Representation:
            - mikro.mixins.Array
            - mikro.structure.Representation
          Sample:
            - mikro.structure.Sample
          Table:
            - mikro.structure.Table
          OmeroFile:
            - mikro.structure.OmeroFile
          Thumbnail:
            - mikro.structure.Thumbnail
          Experiment:
            - mikro.structure.Experiment
